api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:9d13db16bc0a3bfdae6684480c613ee27fc39dcc
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP
  anthropicSecretName: debugpilot-secrets
  anthropicSecretKey: ANTHROPIC_API_KEY
