api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:10dd8cdc20869574b672b5c4a34a9b7485c45a2b
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: LoadBalancer

redis:
  image: redis:alpine
  port: 6379