api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/jobradar-api:7e64057aa446c1b755d12b44d9592966d2fa58cf
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP
  anthropicSecretName: debugpilot-secrets
  anthropicSecretKey: ANTHROPIC_API_KEY
