redis:
  enabled: true

api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/debugpilot-api:e8338ded2b50ded190283b245bf21a132c2f666d
  replicas: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 50
  port: 8000
  imagePullPolicy: Always
  serviceType: ClusterIP
  anthropicSecretName: debugpilot-secrets
  anthropicSecretKey: ANTHROPIC_API_KEY
  redisUrl: redis://redis:6379/0
  publicBaseUrl: https://debugpilot.manavmalavia.org
  authCookieSecure: true
  uploadsS3Bucket: debugpilot-log-uploads-565273632019
  awsRegion: us-east-1
  persistence:
    enabled: false

kafka:
  bootstrapServers: debugpilot-kafka-bootstrap.kafka.svc:9092
  topicIncidents: incidents.raw
  topicDlq: incidents.dlq

consumer:
  enabled: true
  replicas: 1
