redis:
  enabled: true
  image: redis:7-alpine
  port: 6379
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

api:
  image: 565273632019.dkr.ecr.us-east-1.amazonaws.com/debugpilot-api:6726ff9969812946f087c836ec3d7e693ccc9d42
  replicas: 1
  port: 8000
  nodePort: 30080
  imagePullPolicy: Always
  serviceType: ClusterIP
  anthropicSecretName: debugpilot-secrets
  anthropicSecretKey: ANTHROPIC_API_KEY
  redisUrl: redis://redis:6379/0
